-- Active: 1753278632562@@127.0.0.1@3306@Memory
CREATE DATABASE Memory;

Use Memory;

CREATE TABLE Users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE scores (
  id INT AUTO_INCREMENT PRIMARY KEY,
  users_id INT NOT NULL,
  level INT NOT NULL,
  time INT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (users_id) REFERENCES Users(id)
);


